language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer install

after_script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover